power:
  bank: true
  customMob: true
  dlb: true
  PlantCrops: true
CustomMob:
  test:
    spawn: world/10/70/10
    def: SKELETON
    hp: 10
    at: 1
    drop: 1
    cd: 5
GateCreator:
  world/10/10/10: world/10/10/10